### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by Rudd-O** [collective/plonetheme.clean_blog#7] opened 2016-12-04 00:26 UTC
Tried your theme on my site and this URL is 404ing:

/++theme++plonetheme.clean_blog/js/bundle-compiled.js?version=2015-05-28 00%3A00%3A00.000003

This other URL too:

/++theme++plonetheme.clean_blog/css/clean-blog-bundle-compiled.css?version=2015-05-28 00%3A00%3A00.000003

I fail to see what is wrong, but it certainly does not work.  Restarting the Zope server does not change anything either.  As a result of this breakage, the site appears mostly unstyled.

**Comment by vikas-parashar** [comment] 2016-12-11 11:47
I couldn't reproduce it on my machine so closing it for now. Will open if someone else can do that.

**Closed as completed by vikas-parashar** 2016-12-11 11:47 UTC
